Make chroot stuff really works.

diff --git a/lab-anycast-dns/setup b/lab-anycast-dns/setup
--- a/lab-anycast-dns/setup
+++ b/lab-anycast-dns/setup
@@ -4,14 +4,16 @@ LABNAME="anycast-dns"
 # Change ROOT to the directory containing a chrooted system if you
 # don't want to use your own system as a reference
 ROOT=$(readlink -f ${ROOT:-/})
-DEPS="screen ip vde_switch linux bash start-stop-daemon zsh mount.aufs"
-PROGNAME="$0"
+DEPS="screen vde_switch linux start-stop-daemon"
+CHROOTDEPS="ip zsh mount.aufs"
+PROGNAME=$(readlink -f $0)
 PROGARGS="$@"
 
 # Check for dependencies needed by this tool
 check_dependencies() {
+    WHICH=$(which which)
     for dep in $DEPS; do
-        which $dep 2> /dev/null > /dev/null || {
+        $WHICH $dep 2> /dev/null > /dev/null || {
             echo "[!] Missing dependency: $dep"
             exit 1
         }
@@ -19,8 +21,15 @@ check_dependencies() {
     [ -d $ROOT ] || {
         echo "[!] Chroot $ROOT does not exists"
     }
+    for dep in $CHROOTDEPS; do
+        PATH=$ROOT/usr/local/bin:$ROOT/usr/bin:$ROOT/bin:$ROOT/sbin:$ROOT/usr/local/sbin:$ROOT/usr/sbin $WHICH $dep 2> /dev/null > /dev/null || {
+            echo "[!] Missing dependency: $dep (in $ROOT)"
+            exit 1
+        }
+    done
     [ x"$ROOT" = x"/" ] || {
-        cp "$PROGNAME" "$ROOT$PROGNAME"
+        [ -d $(dirname $ROOT/$PROGNAME) ] || mkdir -p $(dirname $ROOT/$PROGNAME)
+        cp "$PROGNAME" "$ROOT/$PROGNAME"
     }
 }
 
@@ -51,7 +60,7 @@ start_vm() {
         start-stop-daemon --make-pidfile --pidfile "$TMP/vm-$name.pid" \
         --start --startas $(which linux) -- \
         uts=$name mem=64M \
-        root=/dev/root rootfstype=hostfs rootflags=$ROOT init=$(readlink -f "$PROGNAME") \
+        root=/dev/root rootfstype=hostfs rootflags=$ROOT init="$PROGNAME" \
         "$@"
     screen -X select 0
 }
@@ -99,7 +108,7 @@ case $$ in
                 echo "[+] Setup AUFS"
                 mount -n -t proc proc /proc
                 mount -n -t sysfs sysfs /sys
-                mount -o bind /usr/lib/uml/modules /lib/modules
+                mount -n -t hostfs hostfs /lib/modules -o /usr/lib/uml/modules,ro
                 mount -n -t tmpfs tmpfs /tmp -o rw,nosuid,nodev
                 mkdir /tmp/ro
                 mkdir /tmp/rw
