multicast: update to a more modern setup
Moreover, use the host kernel for the guest. We switch back to AUFS
and we need to build an initramfs to have the appropriate modules to
mount the host filesystem.

diff --git a/lab-multicast/setup b/lab-multicast/setup
--- a/lab-multicast/setup
+++ b/lab-multicast/setup
@@ -1,135 +1,383 @@
-#!/bin/zsh
+#!/bin/sh
 
-# Some warnings:
-#   - do not run in a screen
-#   - ensure that sudo works accross different terminals
-#   - system vtysh.conf should not use integrated-vtysh-config
+LABNAME="multicast"
+PROGNAME=$(readlink -f $0)
+PROGARGS="$@"
 
-[[ $TERM == "screen" ]] || \
-  exec screen -ln -S lab -c /dev/null -t main "$0" "$@"
-sleep 1
-screen -X caption always "%{= wk}%-w%{= BW}%n %t%{-}%+w %-="
+ROOT=$(readlink -f ${ROOT:-/})
+LINUX=$(readlink -f ${LINUX:-/boot/vmlinuz-$(uname -r)})
 
-_vbe_add_to_bridge() {
-    # Optionally, add it to given bridge
-    [[ -z $2 ]] || {
-	[[ -f /sys/class/net/$2/brforward ]] || {
-	    sudo brctl addbr $2
-	    sudo brctl stp $2 off
-	    sudo ip link set $2 up
-	}
-	[[ -f /sys/class/net/$2/brif/$1 ]] || {
-	    # We need to check if it is in another bridge
-	    bridge=$(echo /sys/class/net/*/brif/$1 2> /dev/null | \
-		sed 's+/sys/class/net/\([^/]*\)/.*+\1+') 2> /dev/null
-	    [[ -n $bridge ]] && \
-		sudo brctl delif $bridge $1
-	    sudo brctl addif $2 $1
+WHICH=$(which which)
+DEPS="tmux vde_switch start-stop-daemon kvm slirpvde busybox"
+CHROOTDEPS="ip pimd keepalived vtysh"
+
+renice 10 -p $$ 2>/dev/null
+
+info() {
+    echo "[1;34m[+] $@[0m"
+}
+
+error() {
+    echo "[1;31m[+] $@[0m"
+}
+
+# Setup a TMP directory
+setup_tmp() {
+    TMP=$(mktemp -d)
+    trap "rm -rf $TMP" EXIT
+    info "TMP is $TMP"
+}
+
+# Check for dependencies needed by this tool
+check_dependencies() {
+    for dep in $DEPS; do
+        $WHICH $dep 2> /dev/null > /dev/null || {
+            error "Missing dependency: $dep"
+            exit 1
         }
+    done
+    [ -d $ROOT ] || {
+        error "Chroot $ROOT does not exists"
     }
+    for dep in $CHROOTDEPS; do
+        PATH=$ROOT/usr/local/bin:$ROOT/usr/bin:$ROOT/bin:$ROOT/sbin:$ROOT/usr/local/sbin:$ROOT/usr/sbin \
+            $WHICH $dep 2> /dev/null > /dev/null || {
+            error "Missing dependency: $dep (in $ROOT)"
+            exit 1
+        }
+    done
 }
 
-tun() {
-    sudo tunctl -b -u $USERNAME -t $1 > /dev/null
-    sudo ip link set up dev $1
-    _vbe_add_to_bridge $1 $2
+# Run our lab in tmux
+setup_screen() {
+    if [ -z "$TMUX" ] || [ x"$(tmux list-panes -F '#{session_name}')" != x"$LABNAME" ]; then
+        unset TMUX
+        exec tmux new-session -s "$LABNAME" -n main "$PROGNAME $PROGARGS"
+    fi
+    sleep 1
+    tmux set-option prefix C-b
+    tmux set-option set-remain-on-exit
+    tmux bind-key r respawn-window
 }
 
+# Setup a VDE switch
+setup_switch() {
+    info "Setup switch $1"
+    start-stop-daemon -b --no-close --make-pidfile --pidfile "$TMP/switch-$1.pid" \
+        --start --startas $($WHICH vde_switch) -- \
+        --sock "$TMP/switch-$1.sock"
+}
 
-# Fix rights
-sudo chmod -R g+rw conf
-sudo chgrp -R quagga conf
+# Build initrd
+setup_initrd() {
+    info "Build initrd"
+    DESTDIR=$TMP/initrd
+    mkdir -p $DESTDIR
 
-#########################
-## Setup interfaces
-#########################
+    # Copy busybox
+    install -D $($WHICH busybox) ${DESTDIR}/bin/busybox
+    for applet in $(${DESTDIR}/bin/busybox --list); do
+        ln -s busybox ${DESTDIR}/bin/${applet}
+    done
 
-echo -n "Setting R1/R2/R3/R4 interfaces... "
-tun tap-R1-eth0 br-BAI1
-tun tap-R1-eth1 br-BAI2
-tun tap-R1-eth2 br-N1
-tun tap-R1-eth3 br-ico1
-tun tap-R2-eth0 br-BAI1
-tun tap-R2-eth1 br-BAI2
-tun tap-R2-eth2 br-N1
-tun tap-R2-eth3 br-ico1
-tun tap-R3-eth0 br-BAI1
-tun tap-R3-eth1 br-BAI2
-tun tap-R3-eth2 br-N2
-tun tap-R3-eth3 br-ico2
-tun tap-R4-eth0 br-BAI1
-tun tap-R4-eth1 br-BAI2
-tun tap-R4-eth2 br-N2
-tun tap-R4-eth3 br-ico2
-echo "OK"
-echo -n "Setting S1/S2/S3/S4 interfaces... "
-tun tap-S1-eth0 br-N1
-tun tap-S2-eth0 br-N2
-tun tap-S3-eth0 br-N2
-tun tap-S4-eth0 br-N2
-echo "OK"
+    # Add libs
+    for x in $(ldd $($WHICH busybox) 2> /dev/null | sed -e '
+               /\//!d;
+               /linux-gate/d;
+               /=>/ {s/.*=>[[:blank:]]*\([^[:blank:]]*\).*/\1/};
+               s/[[:blank:]]*\([^[:blank:]]*\) (.*)/\1/' 2>/dev/null); do
+        install -D "$x" "${DESTDIR}/$x"
+    done
 
-#########################
-## Setup virtual machines
-#########################
+    # Add some modules
+    for mod in 9pnet_virtio 9p aufs virtio_pci; do
+        modprobe --all --set-version="$(uname -r)" \
+            --ignore-install --quiet --show-depends $mod |
+        while read prefix kmod options ; do
+            [ "${prefix}" = "insmod" ] || continue
+            install -D "$kmod" "${DESTDIR}/${kmod}"
+            echo $prefix $kmod $options >> ${DESTDIR}/modules
+        done
+    done
 
-ROUTERS="R1 R2 R3 R4 S1 S2 S3 S4"
-UML="linux root=/dev/root con=null ssl0=fd:0,fd:1 rootfstype=hostfs init=$PWD/uml.sh"
+    # Copy this program
+    cp $PROGNAME ${DESTDIR}/init
 
-# Setup routers
-for R in ${=ROUTERS}; do
-  echo -n "Running $R... "
-  PHYS=""
-  for intf in /sys/class/net/tap-$R-*; do
-    intf=${intf##*/}
-    PHYS="$PHYS ${intf##*-}=tuntap,tap-${R}-${intf##*-},,"
-  done
-  [[ -n "$PHYS" ]] || {
-    echo "abort: no interfaces available"
-    continue
-  }
-  [ -f conf/${R}.sh ] || {
-    echo "abort: missing conf/${R}.sh"
-    continue
-  }
-  chmod +x conf/${R}.sh
-  sleep 0.2
-  screen -t $R sh -c \
-    "$UML uts=${R} ${PHYS} ; echo ; echo 'Terminated' ; sleep 1000"
-  screen -X select 0
-  echo "OK"
-done
+    # Create /tmp
+    mkdir ${DESTDIR}/tmp
 
-# Some help screen
-cat <<EOF
+    # Build initrd
+    cd "${DESTDIR}" && find . | cpio --quiet -R 0:0 -o -H newc | gzip > $TMP/initrd.gz
+}
 
-Some screen commands :
- C-a d     - Detach the screen (resume with screen -r lab)
- C-a "     - Select a window
- C-a space - Next window
- C-a C-a   - Previous window
+# Start a VM
+start_vm() {
+    info "Start VM $1"
+    name="$1"
+    shift
+
+    netargs=""
+    saveifs="$IFS"
+    IFS=,
+    for net in $NET; do
+        mac=$(echo $name-$net | sha1sum | \
+            awk '{print "52:54:" substr($1,0,2) ":" substr($1, 2, 2) ":" substr($1, 4, 2) ":" substr($1, 6, 2)}')
+        netargs="$netargs -net nic,model=virtio,macaddr=$mac,vlan=$net"
+        netargs="$netargs -net vde,sock=$TMP/switch-$net.sock,vlan=$net"
+    done
+    IFS="$saveifs"
+
+    # /root is mounted with version 9p2000.u to allow access to /dev,
+    # /sys and to mount new partitions over them. This is not the case
+    # for 9p2000.L.
+    cat <<EOF > "$TMP/vm-$name.exec"
+#!/bin/sh
+        exec start-stop-daemon --make-pidfile --pidfile "$TMP/vm-$name.pid" \
+        --start --startas $($WHICH kvm) -- \
+        -nodefconfig -no-user-config -nodefaults \
+        -m 128m \
+        -display none \
+        \
+        -chardev stdio,id=charserial0,signal=off \
+        -device isa-serial,chardev=charserial0,id=serial0 \
+        -chardev socket,id=charserial1,path=$TMP/vm-$name-serial.pipe,server,nowait \
+        -device isa-serial,chardev=charserial1,id=serial1 \
+        \
+        -chardev socket,id=con0,path=$TMP/vm-$name-console.pipe,server,nowait \
+        -mon chardev=con0,mode=readline,default \
+        \
+        -fsdev local,security_model=passthrough,id=fsdev-root,path=${ROOT},readonly \
+        -device virtio-9p-pci,id=fs-root,fsdev=fsdev-root,mount_tag=rootshare \
+        -fsdev local,security_model=none,id=fsdev-home,path=${HOME} \
+        -device virtio-9p-pci,id=fs-home,fsdev=fsdev-home,mount_tag=homeshare \
+        -fsdev local,security_model=none,id=fsdev-lab,path=$(dirname "$PROGNAME") \
+        -device virtio-9p-pci,id=fs-lab,fsdev=fsdev-lab,mount_tag=labshare \
+        \
+        -gdb unix:$TMP/vm-$name-gdb.pipe,server,nowait \
+        -kernel $LINUX \
+        -initrd $TMP/initrd.gz \
+        -append "init=$PROGNAME console=ttyS0 uts=$name" \
+        $netargs \
+        $@
 EOF
-echo "Press enter to exit the lab"
-read
+    chmod +x "$TMP/vm-$name.exec"
+    tmux new-window -n $name "$TMP/vm-$name.exec"
+    echo "GDB server listening on.... $TMP/vm-$name-gdb.pipe"
+    echo "monitor listening on....... $TMP/vm-$name-console.pipe"
+    echo "ttyS1 listening on......... $TMP/vm-$name-serial.pipe"
+    tmux select-window -t 1
+}
 
-killall linux
+display_help() {
+    cat <<EOF
 
-# Clean up
-for R in ${=ROUTERS}; do
-  for intf in /sys/class/net/tap-$R-*; do
-    intf=${intf##*/}
-    tunctl -d $intf
-  done
-done
+Some tmux commands (assuming default keybindings) :
+ C-b d     - Detach the lab (resume with "tmux attach -t $LABNAME")
+ C-b w     - Select a window
+ C-b n     - Next window
+ C-b p     - Previous window
+ C-b l     - Last window
+ C-b ?     - Get help
+EOF
+    echo "Press enter to exit the lab"
+    read a
+}
 
-for br in /sys/class/net/*/brif; do
-  [[ $(ls $br | wc -l) -eq 0 ]] && {
-    br=$(basename $(dirname $br))
-    sudo ip link set down dev $br
-    sudo brctl delbr $br
-  }
-done
+cleanup() {
+    for pid in $TMP/*.pid; do
+        kill -15 -$(cat $pid) 2> /dev/null || true
+    done
+    sleep 1
+    for pid in $TMP/*.pid; do
+        kill -9 -$(cat $pid) 2> /dev/null || true
+    done
+    rm -rf $TMP # sh does not seem to handle "trap EXIT"
+    tmux kill-session -t $LABNAME
+}
 
-sudo chown -R ${UID} conf
+start_quagga() {
+    [ -d /lab/$uts/quagga ] || return
+    export VTYSH_PAGER=/bin/cat
+    [ -d /var/log/quagga ] || mkdir /var/log/quagga
+    [ -d /var/run/quagga ] || mkdir /var/run/quagga
+    chown root:root /var/run/quagga
+    for daemon in $(ls /usr/lib/quagga); do
+        conf=/lab/conf/$uts-$daemon.conf
+        [ -f $conf ] || continue
+        info "Running Quagga $daemon"
+        /usr/lib/quagga/$daemon -d -u root -g root -f $conf
+    done
+}
+start_keepalived() {
+    [ -e /lab/conf/$uts-keepalived.conf ] || return
+    info "Running keepalived"
+    keepalived -f /lab/conf/$uts-keepalived.conf
+}
 
-screen -X quit
+start_pimd() {
+    [ -e /lab/conf/$uts-pimd.conf ] || return
+    info "Running pimd"
+    pimd -c /lab/conf/$uts-pimd.conf -N
+}
+
+export STATE=${STATE:-0}
+case $$,$STATE in
+    1,0)
+        # Initrd
+        info "Setup hostname"
+        hostname ${uts}
+        info "Set path"
+        export TERM=screen
+        export PATH=/usr/local/bin:/usr/bin:/bin:/sbin:/usr/local/sbin:/usr/sbin
+        export HOME=/root
+
+        info "Loading modules"
+        . /modules
+
+        info "Setup aufs"
+        mount -t tmpfs tmpfs /tmp -o rw
+        mkdir /tmp/target
+        mkdir /tmp/target/ro
+        mkdir /tmp/target/rw
+        mkdir /tmp/target/overlay
+        mount -t 9p    rootshare /tmp/target/ro      -o trans=virtio,version=9p2000.u,ro
+        mount -t tmpfs tmpfs     /tmp/target/rw      -o rw
+        mount -t aufs  aufs      /tmp/target/overlay -o noxino,noatime,dirs=/tmp/target/rw:/tmp/target/ro=ro
+        mount -n -t proc  proc /tmp/target/overlay/proc
+        mount -n -t sysfs sys  /tmp/target/overlay/sys
+
+        info "Mount home directory on /root"
+        mount -t 9p homeshare /tmp/target/overlay/root -o trans=virtio,version=9p2000.L,access=0,rw
+
+        info "Mount lab directory on /lab"
+        mkdir /tmp/target/overlay/lab
+        mount -t 9p labshare /tmp/target/overlay/lab -o trans=virtio,version=9p2000.L,access=0,rw
+
+        info "Chroot"
+        export STATE=1
+        exec chroot /tmp/target/overlay /lab/setup
+        ;;
+    1,1)
+        # In chroot
+        info "Clean out /tmp and /run directories"
+        for fs in /run /var/run /var/tmp /var/log /tmp; do
+            mount -t tmpfs tmpfs $fs -o rw,nosuid,nodev
+        done
+
+        info "Start udev"
+        /etc/init.d/udev start
+
+        info "Setup interfaces"
+        for intf in /sys/class/net/*; do
+            intf=$(basename $intf)
+            ip a l dev $intf 2> /dev/null >/dev/null || continue
+            case $intf in
+                lo|eth*|dummy*)
+                    ip link set up dev $intf
+                    ;;
+            esac
+        done
+
+        info "Start syslog"
+        rsyslogd
+
+        info "Setup terminal"
+        export STATE=2
+        exec setsid /sbin/getty -L ttyS0 -a root -l "$PROGNAME" -i 115200
+        ;;
+    1,2)
+        export TERM=screen
+
+        info "Lab specific setup"
+        export STATE=3
+        . "$PROGNAME"
+
+        info "Setup additional commands"
+        cat <<EOF > /sbin/reboot
+#!/bin/sh
+echo b > /proc/sysrq-trigger
+EOF
+
+        while true; do
+            info "Spawning a shell"
+            cd $HOME
+            export SSH_TTY=$(tty)
+            if [ -f $HOME/.zshrc ]; then
+                /bin/zsh -i
+            else
+                /bin/bash -i
+            fi || sleep 1
+        done
+        ;;
+    *,3)
+        info "Setup IP addresses"
+        case $uts in
+            R1)
+                ip addr add 10.234.78.65/27 dev eth0
+                ip addr add 10.234.78.97/27 dev eth1
+                ip addr add 172.31.0.1/30 dev eth3
+                ;;
+            R2)
+                ip addr add 10.234.78.66/27 dev eth0
+                ip addr add 10.234.78.98/27 dev eth1
+                ip addr add 172.31.0.2/30 dev eth3
+                ;;
+            R3)
+                ip addr add 10.234.78.67/27 dev eth0
+                ip addr add 10.234.78.99/27 dev eth1
+                ip addr add 172.31.0.1/30 dev eth3
+                ;;
+            R4)
+                ip addr add 10.234.78.68/27 dev eth0
+                ip addr add 10.234.78.100/27 dev eth1
+                ip addr add 172.31.0.2/30 dev eth3
+                ;;
+            S1)
+                ip addr add 10.234.95.2/24 dev eth0
+                ip route add default via 10.234.95.1
+                ;;
+            S*)
+                ip addr add 10.234.72.19$((${uts#S} + 2))/29 dev eth0
+                ip route add default via 10.234.72.193
+                ;;
+        esac
+        start_quagga
+        start_keepalived
+        start_pimd
+        ;;
+    *,*)
+        [ $(id -u) != 0 ] || {
+            error "You should not run this as root"
+            exit 1
+        }
+        check_dependencies
+        setup_screen
+        setup_tmp
+        setup_initrd
+
+        setup_switch   1 # BAI1
+        setup_switch   2 # BAI2
+        setup_switch   11 # N1
+        setup_switch   12 # N2
+        setup_switch   101 # ico1
+        setup_switch   102 # ico2
+        sleep 0.3
+        NET=1,2,11,101 start_vm R1
+        NET=1,2,11,101 start_vm R2
+        NET=1,2,12,102 start_vm R3
+        NET=1,2,12,102 start_vm R4
+        NET=11 start_vm S1
+        NET=12 start_vm S2
+        NET=12 start_vm S3
+        NET=12 start_vm S4
+
+        display_help
+        cleanup
+        ;;
+esac
+
+# Local Variables:
+# mode: sh
+# indent-tabs-mode: nil
+# sh-basic-offset: 4
+# End:
