common: update kernel version check

diff --git a/common/lab-setup b/common/lab-setup
--- a/common/lab-setup
+++ b/common/lab-setup
@@ -316,6 +316,26 @@ spawn () {
     esac
 }
 
+_check_kernel_version() {
+    # Adapted from https://github.com/torvalds/linux/blob/master/scripts/extract-vmlinux
+    # SPDX-License-Identifier: GPL-2.0
+    cmd="$1"
+    sig1="$2"
+    sig2="$3"
+    poss=$(tr "${sig1}\n${sig2}" "\n${sig2}=" < "$KERNEL" | grep -abo "^${sig2}" || true)
+    [ -n "$poss" ] || return 1
+    for pos in $poss; do
+        pos=${pos%%:*}
+        if tail -c+$pos "$KERNEL" | $cmd 2> /dev/null | strings -20 | \
+                grep ^Linux.version; then
+            return 0
+        fi
+    done
+    command -v ${cmd%% *} 2> /dev/null > /dev/null || \
+        log_warn_msg "Command \`$cmd' not found to uncompress $KERNEL"
+    return 1
+}
+
 check_kernel() {
     [ ! -f $TMP/kernel-checked ] || return 0
     log_begin_msg "Checking kernel version"
@@ -325,29 +345,18 @@ check_kernel() {
     # A recent version of `file` is able to extract the
     # information. Since it is not widely available, let use some hack
     # method.
-    VERSION=$(cat <<EOF |
-cat
-gunzip  \\\037\\\213\\\010 xy
-unxz    \\\3757zXZ\\\000   abcde
-bunzip2 BZh                xy
-unlzma  \\\135\\\0\\\0\\\0 xxx
-EOF
-              while read cmd sig1 sig2; do
-                  case $sig1,$sig2 in
-                      ,) poss="0:_" ;;
-                      *) poss=$(tr "${sig1}\n${sig2}" "\n${sig2}=" < "$KERNEL" | grep -abo "^${sig2}" || true) ;;
-                  esac
-                  [ -n "$poss" ] || continue
-                  for pos in $poss; do
-                      pos=${pos%%:*}
-                      tail -c+$pos "$KERNEL" | $cmd 2> /dev/null | strings -20 | \
-                          grep ^Linux.version | head -1
-                  done
-              done | head -1)
-
-    [ -n "$VERSION" ] || log_error_msg "Unable to determine version for $KERNEL"
+    VERSION=$(false \
+                  || _check_kernel_version gunzip    '\037\213\010' xy     \
+                  || _check_kernel_version unxz      '\3757zXZ\000' abcde  \
+                  || _check_kernel_version bunzip2   'BZh'          xy     \
+                  || _check_kernel_version unlzma    '\135\0\0\0'   xxx    \
+                  || _check_kernel_version 'lzop -d' '\211\114\132' xy     \
+                  || _check_kernel_version 'lz4 -d'  '\002!L\030'   xxx    \
+                  || _check_kernel_version unzstd    '(\265/\375'   xxx    \
+                  || true)
     VERSION="${VERSION#Linux version }"
     VERSION="${VERSION%% *}"
+    [ -n "$VERSION" ] || log_error_msg "Unable to determine version for $KERNEL"
     log_ok_msg "Found kernel $VERSION"
 
     log_begin_msg "Check kernel configuration"
