common: try to provide some way to handle namespaces too
This is starting to be very brittle...

diff --git a/common/lab-setup b/common/lab-setup
--- a/common/lab-setup
+++ b/common/lab-setup
@@ -236,6 +236,9 @@ spawn () {
             setup_initrd
             start_vm
             ;;
+        ns)
+            start_ns
+            ;;
         juniper-vrr)
             start_juniper_vrr
             ;;
@@ -401,6 +404,23 @@ setup_initrd () {
     (cd "${DESTDIR}" && find . | cpio --quiet -R 0:0 -o -H newc | gzip > $TMP/initrd.gz)
 
     log_ok_msg "initrd built in $TMP/initrd.gz"
+}
+
+start_ns () {
+    vm=${NAME%%/*}
+    ns=${NAME#*/}
+
+    cat <<EOF  > "$TMP/ns-$vm--$ns.exec"
+while true; do
+    sleep 1
+    ssh -n -F $TMP/ssh_config $vm.lab test -f /tmp/ready || continue
+    break
+done
+ssh -t -F $TMP/ssh_config $vm.lab unshare --pid --mount --uts --fork --mount-proc \
+        env uts=$ns STATE=BEGIN NOGETTY=1 nsenter --net=/run/netns/$ns /mnt/lab/setup
+EOF
+    chmod +x "$TMP/ns-$vm--$ns.exec"
+    tmux new-window -d -n $NAME "$TMP/ns-$vm--$ns.exec"
 }
 
 start_vm () {
@@ -1107,7 +1127,7 @@ export STATE=${STATE:-BEGIN}
 case $$,$STATE in
     1,BEGIN)
         # In initrd
-        log_info_msg "initrd started"
+        log_info_msg "image started for $uts"
         hostname ${uts}
         export PATH=/usr/local/bin:/usr/bin:/bin:/sbin:/usr/local/sbin:/usr/sbin
         export HOME=/root
@@ -1117,68 +1137,77 @@ case $$,$STATE in
             . /modules
         }
 
-        log_begin_msg "Setup root file system"
-        mount -n -t tmpfs tmpfs /tmp -o rw
-        mkdir /tmp/target
-        mkdir /tmp/target/ro
-        mkdir /tmp/target/overlay
-        mount -n -t 9p    rootshare /tmp/target/ro      -o trans=virtio,version=9p2000.u,ro
-        mkdir /tmp/target/rw
-        mount -n -t tmpfs tmpfs     /tmp/target/rw      -o rw
-        mkdir /tmp/target/rw/workdir
-        mkdir /tmp/target/rw/upperdir
-        mount -n -t aufs aufs /tmp/target/overlay \
-              -o noxino,noatime,dirs=/tmp/target/rw/upperdir:/tmp/target/ro=ro \
-              2> /dev/null || \
-            mount -n -t overlayfs overlayfs /tmp/target/overlay \
-                  -o lowerdir=/tmp/target/ro,upperdir=/tmp/target/rw/upperdir,noatime \
+        overlay=/
+        [ ! -f /init ] || {
+            overlay=/tmp/target/overlay
+            log_begin_msg "Setup root file system"
+            mount -n -t tmpfs tmpfs /tmp -o rw
+            mkdir /tmp/target
+            mkdir /tmp/target/ro
+            mkdir /tmp/target/overlay
+            mount -n -t 9p    rootshare /tmp/target/ro      -o trans=virtio,version=9p2000.u,ro
+            mkdir /tmp/target/rw
+            mount -n -t tmpfs tmpfs     /tmp/target/rw      -o rw
+            mkdir /tmp/target/rw/workdir
+            mkdir /tmp/target/rw/upperdir
+            mount -n -t aufs aufs /tmp/target/overlay \
+                  -o noxino,noatime,dirs=/tmp/target/rw/upperdir:/tmp/target/ro=ro \
                   2> /dev/null || \
-            mount -n -t overlay overlayfs /tmp/target/overlay \
-                  -o lowerdir=/tmp/target/ro,upperdir=/tmp/target/rw/upperdir,workdir=/tmp/target/rw/workdir,noatime \
-                  2> /dev/null ||
-            log_error_msg "Unable to mount AUFS/overlayfs"
-        mount -n -t proc  proc /tmp/target/overlay/proc
-        mount -n -t sysfs sys  /tmp/target/overlay/sys
-        log_ok_msg "Root file system setup"
+                mount -n -t overlayfs overlayfs /tmp/target/overlay \
+                      -o lowerdir=/tmp/target/ro,upperdir=/tmp/target/rw/upperdir,noatime \
+                      2> /dev/null || \
+                mount -n -t overlay overlayfs /tmp/target/overlay \
+                      -o lowerdir=/tmp/target/ro,upperdir=/tmp/target/rw/upperdir,workdir=/tmp/target/rw/workdir,noatime \
+                      2> /dev/null ||
+                log_error_msg "Unable to mount AUFS/overlayfs"
+            mount -n -t proc  proc  /tmp/target/overlay/proc
+            mount -n -t tmpfs tmpfs /tmp/target/overlay/mnt
+            log_ok_msg "Root file system setup"
+        }
 
         log_begin_msg "Clean /tmp and /run"
-        for fs in /run /var/run /var/tmp /var/log /tmp /mnt; do
-            if [ -d /tmp/target/overlay$fs ] && [ ! -h /tmp/target/overlay$fs ]; then
-                mount -t tmpfs tmpfs /tmp/target/overlay$fs -o rw,nosuid,nodev
+        mount -n -t sysfs sys $overlay/sys
+        for fs in /run /var/run /var/tmp /var/log /tmp; do
+            if [ -d $overlay$fs ] && [ ! -h $overlay$fs ]; then
+                mount -t tmpfs tmpfs $overlay$fs -o rw,nosuid,nodev
             fi
         done
         log_ok_msg "/tmp, /run and others are clean"
 
-        log_begin_msg "Mount /root"
-        mount -t 9p homeshare /tmp/target/overlay/root -o trans=virtio,version=9p2000.L,access=any,rw || \
-            log_error_msg "Unable to mount /root"
-        [ ! -d /tmp/target/overlay/root/.ssh ] || {
-            mount -t tmpfs tmpfs /tmp/target/overlay/root/.ssh -o rw,nosuid,nodev
-            chmod 0700 /tmp/target/overlay/root/.ssh
+        [ ! -f /init ] || {
+            log_begin_msg "Mount /root"
+            mount -t 9p homeshare /tmp/target/overlay/root -o trans=virtio,version=9p2000.L,access=any,rw || \
+                log_error_msg "Unable to mount /root"
+            [ ! -d /tmp/target/overlay/root/.ssh ] || {
+                mount -t tmpfs tmpfs /tmp/target/overlay/root/.ssh -o rw,nosuid,nodev
+                chmod 0700 /tmp/target/overlay/root/.ssh
+            }
+            log_ok_msg "/root mounted"
+            log_begin_msg "Mount /lib/modules"
+            mount -t 9p moduleshare /tmp/target/overlay/lib/modules -o trans=virtio,version=9p2000.L,access=0,ro || \
+                log_error_msg "Unable to mount /lib/modules"
+            log_ok_msg "/root and /lib/modules mounted"
+
+            log_begin_msg "Mount /mnt/lab"
+            mkdir /tmp/target/overlay/mnt/lab /tmp/target/overlay/mnt/common
+            mount -t 9p labshare /tmp/target/overlay/mnt/lab -o trans=virtio,version=9p2000.L,access=any,rw || \
+                log_error_msg "Unable to mount /mnt/lab"
+            mount -t 9p commonshare /tmp/target/overlay/mnt/common -o trans=virtio,version=9p2000.L,access=any,ro || \
+                log_error_msg "Unable to mount /mnt/common"
+            log_ok_msg "/mnt/lab and /mnt/common mounted"
+
+            log_begin_msg "Mount /tmp/lab"
+            mkdir /tmp/target/overlay/tmp/lab
+            mount -t 9p tmpshare /tmp/target/overlay/tmp/lab -o trans=virtio,version=9p2000.L,access=any,rw || \
+                log_error_msg "Unable to mount /tmp/lab"
+            log_ok_msg "/tmp/lab mounted"
+
+            log_info_msg "Change root"
+            export STATE=CHROOTED
+            exec chroot /tmp/target/overlay /mnt/lab/setup
         }
-        log_ok_msg "/root mounted"
-        log_begin_msg "Mount /lib/modules"
-        mount -t 9p moduleshare /tmp/target/overlay/lib/modules -o trans=virtio,version=9p2000.L,access=0,ro || \
-            log_error_msg "Unable to mount /lib/modules"
-        log_ok_msg "/root and /lib/modules mounted"
-
-        log_begin_msg "Mount /mnt/lab"
-        mkdir /tmp/target/overlay/mnt/lab /tmp/target/overlay/mnt/common
-        mount -t 9p labshare /tmp/target/overlay/mnt/lab -o trans=virtio,version=9p2000.L,access=any,rw || \
-            log_error_msg "Unable to mount /mnt/lab"
-        mount -t 9p commonshare /tmp/target/overlay/mnt/common -o trans=virtio,version=9p2000.L,access=any,ro || \
-            log_error_msg "Unable to mount /mnt/common"
-        log_ok_msg "/mnt/lab and /mnt/common mounted"
-
-        log_begin_msg "Mount /tmp/lab"
-        mkdir /tmp/target/overlay/tmp/lab
-        mount -t 9p tmpshare /tmp/target/overlay/tmp/lab -o trans=virtio,version=9p2000.L,access=any,rw || \
-            log_error_msg "Unable to mount /tmp/lab"
-        log_ok_msg "/tmp/lab mounted"
-
-        log_info_msg "Change root"
         export STATE=CHROOTED
-        exec chroot /tmp/target/overlay /mnt/lab/setup
+        exec /mnt/lab/setup
         ;;
 
     1,CHROOTED)
@@ -1197,18 +1226,20 @@ EOF
         mount --bind /tmp/hosts /etc/hosts
         log_ok_msg "/etc/hosts configured"
 
-        log_begin_msg "Starting udev"
-        udev_log=err
-        mount -n -o size=10M,mode=0755 -t devtmpfs devtmpfs /dev
-        rm -f /etc/udev/rules.d/70-persistent-net.rules
-        udevadm info --cleanup-db
-        for udev in /lib/systemd/systemd-udevd /usr/lib/systemd/systemd-udevd $(command -v udevd 2> /dev/null); do
-            [ ! -x $udev ] || break
-        done
-        $udev --daemon
-        udevadm trigger --action=add
-        udevadm settle
-        log_ok_msg "udev started"
+        mount | grep -q '^devtmpfs' || {
+            log_begin_msg "Starting udev"
+            udev_log=err
+            mount -n --make-private -o size=10M,mode=0755 -t devtmpfs devtmpfs /dev
+            rm -f /etc/udev/rules.d/70-persistent-net.rules
+            udevadm info --cleanup-db
+            for udev in /lib/systemd/systemd-udevd /usr/lib/systemd/systemd-udevd $(command -v udevd 2> /dev/null); do
+                [ ! -x $udev ] || break
+            done
+            $udev --daemon
+            udevadm trigger --action=add
+            udevadm settle
+            log_ok_msg "udev started"
+        }
 
         [ ! -f /proc/sys/kernel/core_pattern ] || {
             ulimit -c unlimited
@@ -1259,10 +1290,17 @@ EOF
         done
 
 
-        log_info_msg "Setup terminal"
         unset SHLVL
-        export STATE=GETTY
-        exec setsid /sbin/agetty -L ttyS0 -a root -l /mnt/lab/setup -i 115200 $TERM
+        if [ -n "$NOGETTY" ]; then
+            export STATE=SETUP
+            . /mnt/lab/setup
+            export STATE=SHELL
+            exec /mnt/lab/setup
+        else
+            log_info_msg "Setup terminal"
+            export STATE=GETTY
+            exec setsid /sbin/agetty -L ttyS0 -a root -l /mnt/lab/setup -i 115200 $TERM
+        fi
         ;;
 
     1,GETTY)
@@ -1291,7 +1329,12 @@ EOF
         export PATH=/tmp/tools:/mnt/common/bin:$PATH
         export STATE=SETUP
         . /mnt/lab/setup
+        touch /tmp/ready
+        export STATE=SHELL
+        exec /mnt/lab/setup
+        ;;
 
+    *,SHELL)
         while true; do
             log_info_msg "Spawning a shell"
             cd /mnt/lab
